wandb_version: 1

batch_size:
  desc: null
  value: 256
n_units:
  desc: null
  value: 31
learning_rate:
  desc: null
  value: 0.01
lr_decay:
  desc: null
  value: 0.8827934367716966
lr_step:
  desc: null
  value: 7
ns:
  desc: null
  value: 7
loss:
  desc: null
  value: mse
update_freq:
  desc: null
  value: 29
PPO:
  desc: null
  value: 0
CQL:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710812096.112176
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.0
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
