wandb_version: 1

batch_size:
  desc: null
  value: 128
n_units:
  desc: null
  value: 17
learning_rate:
  desc: null
  value: 5.0e-06
lr_decay:
  desc: null
  value: 0.8125914169715954
lr_step:
  desc: null
  value: 7
ns:
  desc: null
  value: 16
loss:
  desc: null
  value: smooth_l1
update_freq:
  desc: null
  value: 54
PPO:
  desc: null
  value: 0
CQL:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710787359.014466
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.0
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
